import fs from "node:fs";
import readline from "node:readline";

/*
Generate pluralYous.mjs from resources/bsb_you_counts.tsv + resources/bsb_tables.tsv.

The app (compile.mjs) counts you-words POSITIONALLY per verse: `youCount`
increments only for the literal tokens you/your/yours (see compile.mjs
parseDivineNamesAndYalls).  So the per-verse boolean arrays in the build-time
module must contain one entry per you/your/yours token, in reading order --
our resolved data (bsb_you_counts.tsv) records every you-family token
(you/your/yours/ye/yourself/yourselves) in gloss order, so we walk the same
glosses, consume the booleans in lockstep, and keep only you/your/yours.
*/

const COUNTS = "resources/bsb_you_counts.tsv";
const TABLES = "resources/bsb_tables.tsv";
const OUT = "pluralYous.mjs";

const EN_COL = 19;
const VERSE_ID_COL = 13;

const YOU_RE = /\b(ye|you|your|yours|yourself|yourselves)\b/gi;
const KEPT_RE = /\b(you|your|yours)\b/i;

async function main() {
  const counts = new Map();
  for (const line of fs.readFileSync(COUNTS, "utf8").split("\n")) {
    const tab = line.indexOf("\t");
    if (tab < 0) continue;
    counts.set(line.slice(0, tab).toLowerCase(), JSON.parse(line.slice(tab + 1)));
  }
  console.error("Loaded", counts.size, "verses from", COUNTS);

  const perVerse = new Map(); // verseId -> array of { word, plural }
  const rl = readline.createInterface({
    input: fs.createReadStream(TABLES),
    crlfDelay: Infinity,
  });
  let first = true;
  let key = null; // lowercase "book chapter:verse" form, e.g. "genesis 1:29"
  let ctx = null;
  for await (const line of rl) {
    if (first) {
      first = false;
      continue;
    }
    const f = line.split("\t");
    const id = (f[VERSE_ID_COL - 1] || "").trim();
    if (id) {
      key = id.toLowerCase();
      if (!perVerse.has(key)) perVerse.set(key, []);
      ctx = perVerse.get(key);
    }
    if (!ctx) continue;
    const gloss = f[EN_COL - 1] || "";
    for (const m of gloss.matchAll(YOU_RE)) {
      ctx.push({ word: m[0], plural: null, row: id });
    }
  }

  let kept = 0;
  let dropped = 0;
  let missing = 0;
  const out = {};
  let asserted = 0;
  for (const [key, tokens] of perVerse) {
    const booleans = counts.get(key);
    if (booleans === undefined) {
      missing++;
      continue;
    }
    if (tokens.length !== booleans.length) {
      throw new Error(
        `Mismatch in ${key}: ${tokens.length} you-tokens in gloss but ${booleans.length} booleans in counts`
      );
    }
    asserted++;
    let i = 0;
    const keptBooleans = [];
    for (const t of tokens) {
      t.plural = booleans[i++];
      if (KEPT_RE.test(t.word)) {
        keptBooleans.push(t.plural);
        kept++;
      } else {
        dropped++;
      }
    }
    if (keptBooleans.length > 0) out[key] = keptBooleans;
  }

  console.error(
    `Asserted lengths for ${asserted} verses (${missing} verses from tables had no counts row); `
  );
  console.error(
    `kept ${kept} you/your/yours booleans, dropped ${dropped} (ye/yourself/yourselves)`
  );
  console.error("Verses with at least one you/your/yours:", Object.keys(out).length);

  const body = [
    "/*",
    "Generated by `node scripts/build-plurals.mjs` from resources/bsb_you_counts.tsv",
    "and resources/bsb_tables.tsv. Do not edit by hand.",
    "*/",
    "",
    "var youData = {",
    ...Object.entries(out).map(
      ([k, arr]) => `\t"${k}": [${arr.map((b) => (b ? "1" : "0")).join(", ")}],`
    ),
    "};",
    "",
    "// You words are counted positionally per verse (0-based) - see compile.mjs.",
    "// In each verse's array, 1 = plural (2p), 0 = singular (2s).",
    "// book is a dash-less slug like \"1-chronicles\".",
    "function verseArr(book, chapter, verse) {",
    '\treturn youData[book.replaceAll("-", " ") + " " + chapter + ":" + verse];',
    "}",
    "function isPlural(book, chapter, verse, youCount) {",
    "\tvar arr = verseArr(book, chapter, verse);",
    "\treturn !!arr && arr[youCount] === 1;",
    "}",
    "function isSingular(book, chapter, verse, youCount) {",
    "\tvar arr = verseArr(book, chapter, verse);",
    "\treturn !!arr && arr[youCount] === 0;",
    "}",
    "",
    "export { isPlural, isSingular }",
    "",
  ].join("\n");

  fs.writeFileSync(OUT, body);
  console.error("Wrote", OUT, `(${body.length} bytes)`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});